namespace: documentdb-operator
replicaCount: 1

# DocumentDB version - global default for all components when individual tags are not set
# Priority: individual component tag > documentDbVersion > Chart.appVersion
# Defaults to Chart.appVersion if not specified  
documentDbVersion: ""

# Telemetry configuration for Application Insights
telemetry:
  # Enable or disable telemetry collection
  enabled: true
  # Application Insights instrumentation key (provide either this or connectionString)
  instrumentationKey: ""
  # Application Insights connection string (alternative to instrumentationKey)
  connectionString: ""
  # Name of existing secret containing telemetry credentials
  # Secret should have keys: APPINSIGHTS_INSTRUMENTATIONKEY or APPLICATIONINSIGHTS_CONNECTION_STRING
  existingSecret: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "documentdb-operator"
  
# WAL Replica feature flag
walReplica: false  # Set to true to deploy the WAL replica plugin

image:
  documentdbk8soperator:
    repository: ghcr.io/documentdb/documentdb-kubernetes-operator/operator
    pullPolicy: Always
  sidecarinjector:
    repository: ghcr.io/documentdb/documentdb-kubernetes-operator/sidecar
    pullPolicy: Always
  walreplica:
    repository: ghcr.io/documentdb/documentdb-kubernetes-operator/wal-replica
    pullPolicy: Always
cloudnative-pg:
  namespaceOverride: cnpg-system
